name: e2e tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build images
        run: docker-compose build

      - name: run e2e tests
        run: docker compose up --abort-on-container-exit --exit-code-from=e2e-tests

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            test-results/
            e2e/session.json
          retention-days: 10
